pypistats/models/user.py
"""User tables."""
import datetime

from flask_login import UserMixin
from sqlalchemy.dialects.postgresql import ARRAY

from pypistats.database import Column
from pypistats.database import Model
from pypistats.database import SurrogatePK
from pypistats.extensions import db

MAX_FAVORITES = 20


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = "users"

    uid = Column(db.Integer(), unique=True)
    username = Column(db.String(39), nullable=False)
    avatar_url = Column(db.String(256))
    token = Column(db.String(256))
    created_at = Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)
    favorites = Column(ARRAY(db.String(128), dimensions=1))

    def __init__(self, token, **kwargs):
        """Create instance."""
        db.Model.__init__(self, token=token, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"<User({self.username})>"

pypistats/views/api.py
"""JSON API routes."""
from flask import Blueprint
from flask import abort
from flask import g
from flask import jsonify
from flask import render_template
from flask import request

from pypistats.models.download import RECENT_CATEGORIES
from pypistats.models.download import OverallDownloadCount
from pypistats.models.download import PythonMajorDownloadCount
from pypistats.models.download import PythonMinorDownloadCount
from pypistats.models.download import RecentDownloadCount
from pypistats.models.download import SystemDownloadCount

blueprint = Blueprint("api", __name__, url_prefix="/api")


@blueprint.route("/")
def api():
    """Get API documentation."""
    return render_template("api.html", user=g.user)


@blueprint.route("/packages/<package>/recent")
def api_downloads_recent(package):
    """Get the recent downloads of a package."""
    # abort(503)
    if package != "__all__":
        package = package.replace(".", "-").replace("_", "-")
    category = request.args.get("period")
    if category is None:
        downloads = RecentDownloadCount.query.filter_by(package=package).all()
    elif category in RECENT_CATEGORIES:
        downloads = RecentDownloadCount.query.filter_by(package=package, category=category).all()
    else:
        abort(404)

    response = {"package": package, "type": "recent_downloads"}
    if len(downloads) > 0:
        if category is None:
            response["data"] = {"last_" + rc: 0 for rc in RECENT_CATEGORIES}
        else:
            response["data"] = {"last_" + category: 0}
        for r in downloads:
            response["data"]["last_" + r.category] = r.downloads
    else:
        abort(404)

    return jsonify(response)


@blueprint.route("/packages/<package>/overall")
def api_downloads_overall(package):
    """Get the overall download time series of a package."""
    # abort(503)
    if package != "__all__":
        package = package.replace(".", "-").replace("_", "-")
    mirrors = request.args.get("mirrors")
    if mirrors == "true":
        downloads = (
            OverallDownloadCount.query.filter_by(package=package, category="with_mirrors")
            .order_by(OverallDownloadCount.date)
            .all()
        )
    elif mirrors == "false":
        downloads = (
            OverallDownloadCount.query.filter_by(package=package, category="without_mirrors")
            .order_by(OverallDownloadCount.date)
            .all()
        )
    else:
        downloads = (
            OverallDownloadCount.query.filter_by(package=package)
            .order_by(OverallDownloadCount.category, OverallDownloadCount.date)
            .all()
        )

    response = {"package": package, "type": "overall_downloads"}
    if len(downloads) > 0:
        response["data"] = [{"date": str(r.date), "category": r.category, "downloads": r.downloads} for r in downloads]
    else:
        abort(404)

    return jsonify(response)


@blueprint.route("/packages/<package>/python_major")
def api_downloads_python_major(package):
    """Get the python major download time series of a package."""
    return generic_downloads(PythonMajorDownloadCount, package, "version", "python_major")


@blueprint.route("/packages/<package>/python_minor")
def api_downloads_python_minor(package):
    """Get the python minor download time series of a package."""
    return generic_downloads(PythonMinorDownloadCount, package, "version", "python_minor")


@blueprint.route("/packages/<package>/system")
def api_downloads_system(package):
    """Get the system download time series of a package."""
    return generic_downloads(SystemDownloadCount, package, "os", "system")


def generic_downloads(model, package, arg, name):
    """Generate a generic response."""
    # abort(503)
    if package != "__all__":
        package = package.replace(".", "-").replace("_", "-")
    category = request.args.get(arg)
    if category is not None:
        downloads = model.query.filter_by(package=package, category=category.title()).order_by(model.date).all()
    else:
        downloads = model.query.filter_by(package=package).order_by(model.category, model.date).all()

    response = {"package": package, "type": f"{name}_downloads"}
    if downloads is not None:
        response["data"] = [{"date": str(r.date), "category": r.category, "downloads": r.downloads} for r in downloads]
    else:
        abort(404)

    return jsonify(response)


# TODO
# @blueprint.route("/top/overall")
# def api_top_packages():
#     """Get the most downloaded packages by recency."""
#     return "top overall"
#
#
# @blueprint.route("/top/python_major")
# def api_top_python_major():
#     """Get the most downloaded packages by python major version."""
#     return "top python_major"
#
#
# @blueprint.route("/top/python_minor")
# def api_top_python_minor():
#     """Get the most downloaded packages by python minor version."""
#     return "top python_minor"
#
#
# @blueprint.route("/top/system")
# def api_top_system():
#     """Get the most downloaded packages by system."""
#     return "top python_minor"

pypistats/views/user.py
"""User page for tracking packages."""
from flask import Blueprint
from flask import abort
from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for

from pypistats.extensions import github
from pypistats.models.download import RecentDownloadCount
from pypistats.models.user import MAX_FAVORITES
from pypistats.models.user import User

blueprint = Blueprint("user", __name__, template_folder="templates")


@github.access_token_getter
def token_getter():
    """Get the token for a user."""
    this_user = g.user
    if this_user is not None:
        return this_user.token


@blueprint.route("/github-callback")
@github.authorized_handler
def authorized(oauth_token):
    """Github authorization callback."""
    next_url = request.args.get("next") or url_for("user.user")
    if oauth_token is None:
        flash("Authorization failed.")
        return redirect(next_url)

    # Ensure a user with token doesn't already exist
    this_user = User.query.filter_by(token=oauth_token).first()
    if this_user is None:
        this_user = User(token=oauth_token)

    # Set this to use API to get user data
    g.user = this_user
    user_data = github.get("user")

    # extract data
    uid = user_data["id"]
    username = user_data["login"]
    avatar_url = user_data["avatar_url"]

    # Create/update the user
    this_user = User.query.filter_by(uid=uid).first()
    if this_user is None:
        this_user = User(token=oauth_token, uid=uid, username=username, avatar_url=avatar_url)
    else:
        this_user.username = username
        this_user.avatar_url = avatar_url
        this_user.token = oauth_token

    this_user.save()

    session["username"] = this_user.username
    session["user_id"] = this_user.id
    g.user = this_user

    return redirect(next_url)


@blueprint.route("/login")
def login():
    """Login via GitHub OAuth."""
    if session.get("user_id", None) is None:
        return github.authorize()
    else:
        return redirect(url_for("user.user"))


@blueprint.route("/logout")
def logout():
    """Logout."""
    session.pop("user_id", None)
    session.pop("username", None)
    g.user = None
    return redirect(url_for("general.index"))


@blueprint.route("/user")
def user():
    """Render the user's personal page."""
    return render_template("user.html", user=g.user)


@blueprint.route("/user/packages/<package>")
def user_package(package):
    """Handle adding and deleting packages to user's list."""
    if g.user:
        # Ensure package is valid.
        downloads = RecentDownloadCount.query.filter_by(package=package).all()

        # Handle add/remove to favorites
        if g.user.favorites is None:
            # Ensure package is valid before adding
            if len(downloads) == 0:
                return abort(400)
            g.user.favorites = [package]
            g.user.update()
            return redirect(url_for("user.user"))
        elif package in g.user.favorites:
            favorites = g.user.favorites
            favorites.remove(package)
            # Workaround for sqlalchemy mutable ARRAY types
            g.user.favorites = None
            g.user.save()
            g.user.favorites = favorites
            g.user.save()
            return redirect(url_for("user.user"))
        else:
            if len(g.user.favorites) < MAX_FAVORITES:
                # Ensure package is valid before adding
                if len(downloads) == 0:
                    return abort(400)
                favorites = g.user.favorites
                favorites.append(package)
                favorites = sorted(favorites)
                # Workaround for sqlalchemy mutable ARRAY types
                g.user.favorites = None
                g.user.save()
                g.user.favorites = favorites
                g.user.save()
                return redirect(url_for("user.user"))
            else:
                return f"Maximum package number reached ({MAX_FAVORITES})."
    return abort(400)

pypistats/templates/about.html
{% extends "layout.html" %}
{% block title %}PyPI Download Stats{% endblock %}
{% block body %}
    <h1>About PyPI Stats</h1>
    <hr>
    <h3>Goal</h3>
    <p>PyPI Stats aims to provide aggregate download information on python packages available from the Python Package
        Index in lieu of having to execute queries against raw download records in Google BigQuery.</p>
    <h3>Data</h3>
    <p>Download stats are sourced from the Python Software Foundation's publicly available
        <a href="https://bigquery.cloud.google.com/table/bigquery-public-data:pypi.downloads">download stats</a>
        on Google BigQuery. All aggregate download stats ignore known PyPI mirrors (such as
        <a href="{{ url_for('general.package_page', package='bandersnatch') }}">bandersnatch</a>) unless noted
        otherwise.</p>
    <p>PyPI Stats retains data for 180 days.</p>
    <h3>API</h3>
    <p>A simple
        <a href="{{ url_for('api.api') }}">JSON API</a>
        is available for aggregate download stats and time series for packages.</p>
    <h3>Downstream</h3>
    <p>
    <ul>
        <li>
            <a href="{{ url_for('general.package_page', package='pypistats') }}">pypistats</a> is a <a
                href="https://github.com/hugovk/pypistats">python package</a> that provides a client and CLI tool for
            the pypistats.org JSON API</a>
        </li>
        <li>
            <a href="https://shields.io/#/examples/downloads">shields.io</a> uses the pypistats.org JSON API to provide
            download count badges, like this one for <a
                href="{{ url_for('general.package_page', package='pypistats') }}">pypistats</a> <a
                href="https://github.com/hugovk/pypistats"><img src="https://img.shields.io/pypi/dm/pypistats.svg"></a>
        </li>
    </ul>
    <p>PyPIStats.org is also <a href="https://github.com/crflynn/pypistats.org">open source</a>.</p>
    <h3>Who</h3>
    <p>PyPI Stats was created by
        <a href="https://flynn.gg">Christopher Flynn</a>.
    </p>
    <p>
        Thanks to <a href="https://github.com/hugovk">Hugo (hugovk)</a> for providing a client interface to the API.
    </p>

{% endblock %}

pypistats/templates/admin.html
{% extends "layout.html" %}
{% block title %}PyPI Download Stats{% endblock %}
{% block body %}
    <h1>Analytics for PyPI packages</h1>
    <hr>
    <form method="POST" action="/admin">
        {{ form.csrf_token }}
        {{ form.date.label }}
        {{ form.date(size=24) }}
        <input type="submit" value="Submit">
    </form>
    <br>
    {% if not date %}
        <p>Submit date to run backfill.</p>
    {% endif %}
    {% if date %}
        <br>
        {{ date }} submitted.
    {% endif %}
{% endblock %}

pypistats/templates/api.html
{% extends "layout.html" %}
{% block title %}PyPI Download Stats{% endblock %}
{% block body %}
    <h1>PyPI Stats API</h1>
    <hr>
    <p>
        PyPI Stats provides a simple JSON API for retrieving aggregate download stats and time series for packages. The
        following are the valid endpoints using host:
        <code>https://pypistats.org/</code>
    </p>
    <h2>NOTES</h2>
    <p>
    <ul>
        <li>All download stats exclude known mirrors (such as
            <a href="{{ url_for('general.package_page', package='bandersnatch') }}">bandersnatch</a>) unless noted
            otherwise.
        </li>
        <li>Time series data is retained only for 180 days.</li>
        <li>All download data is updated once daily.</li>
    </ul>
    </p>
    <h2>Etiquette</h2>
    <p>
        If you plan on using the API to download historical data for every python package in the database (e.g. for some
        personal data exploration), <b>DON'T</b>. This website runs on limited resources and you will degrade
        the site performance by doing this. It will also take a very long time.
    </p>
    <p>
        You are much better off extracting the data directly from the Google
        BigQuery <a href="https://bigquery.cloud.google.com/table/bigquery-public-data:pypi.downloads">pypi downloads tables</a>. You
        can query up to 1TB of data FREE every month before having to pay. The volume of data queried for this website
        falls well under that limit (each month of data is less than 100 GB queried) and you will have your data
        in a relatively short amount of time. <a
            href="https://packaging.python.org/guides/analyzing-pypi-package-downloads/">Here is a quick guide</a>.
    </p>
    <p>
        If you want to regularly fetch download counts for a particular package or set of packages, cache your results.
        The data provided here is updated <b>once</b> daily, so you should not need to fetch results from the same API
        endpoint more than once per day.
    </p>
    <h2>Rate Limiting</h2>
    <p>
        IP-based rate limiting is imposed application-wide.
    </p>
    <h2>API Client</h2>
    <p>
        The <a href="{{ url_for('general.package_page', package='pypistats') }}">pypistats</a> <a
            href="https://pypi.org/project/pypistats">package</a> is a python client and CLI tool for easily
        accessing, aggregating, and formatting results from the API. To install, use pip:
    <pre><code>pip install -U pypistats</code></pre>
    Refer to the <a href="https://github.com/hugovk/pypistats">documentation</a> for usage.
    </p>
    <h2>Endpoints</h2>
    <h3>/api/packages/&lt;package&gt;/recent</h3>
    <p>Retrieve the aggregate download quantities for the last day/week/month.
    </p>
    <p>Query arguments:
    <ul>
        <li>
            <b>period</b>
            (optional):
            <code>day</code>
            or
            <code>week</code>
            or
            <code>month</code>. If omitted returns all values.
        </li>
    </ul>
    Example response:
    <pre><code>{
  "data": {
    "last_day": 1,
    "last_month": 2,
    "last_week": 3
  },
  "package": "package_name",
  "type": "recent_downloads"
}</code></pre>
    </p>
    <h3>/api/packages/&lt;package&gt;/overall</h3>
    <p>Retrieve the aggregate daily download time series with or without mirror downloads.
    </p>
    <p>Query arguments:
    <ul>
        <li>
            <b>mirrors</b>
            (optional):
            <code>true</code>
            or
            <code>false</code>. If omitted returns both series data.
        </li>
        <!-- <li> <b>start_date</b> (optional): starting date of time series in format <code>YYYY-MM-DD</code> </li> <li> <b>end_date</b> (optional): ending date of time series in format <code>YYYY-MM-DD</code> </li> -->
    </ul>
    Example response:
    <pre><code>{
  "data": [
    {
      "category": "with_mirrors",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "without_mirrors",
      "date": "2018-02-08",
      "downloads": 1
    }
  ],
  "package": "package_name",
  "type": "overall_downloads"
}</code></pre>
    </p>
    <h3>/api/packages/&lt;package&gt;/python_major</h3>
    <p>Retrieve the aggregate daily download time series by Python major version number.
    </p>
    <p>Query arguments:
    <ul>
        <li>
            <b>version</b>
            (optional): the Python major version number, e.g.
            <code>2</code>
            or
            <code>3</code>. If omitted returns all series data (including
            <code>null</code>).
        </li>
        <!-- <li> <b>start_date</b> (optional): starting date of time series in format <code>YYYY-MM-DD</code> </li> <li> <b>end_date</b> (optional): ending date of time series in format <code>YYYY-MM-DD</code> </li> -->
    </ul>
    Example response:
    <pre><code>{
  "data": [
    {
      "category": "2",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "3",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "null",
      "date": "2018-02-08",
      "downloads": 1
    }
  ],
  "package": "package_name",
  "type": "python_major_downloads"
}</code></pre>
    </p>
    <h3>/api/packages/&lt;package&gt;/python_minor</h3>
    <p>Retrieve the aggregate daily download time series by Python minor version number.
    </p>
    <p>Query arguments:
    <ul>
        <li>
            <b>version</b>
            (optional): the Python major version number, e.g.
            <code>2.7</code>
            or
            <code>3.6</code>. If omitted returns all series data (including
            <code>null</code>).
        </li>
        <!-- <li> <b>start_date</b> (optional): starting date of time series in format <code>YYYY-MM-DD</code> </li> <li> <b>end_date</b> (optional): ending date of time series in format <code>YYYY-MM-DD</code> </li> -->
    </ul>
    Example response:
    <pre><code>{
  "data": [
    {
      "category": "2.6",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "2.7",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "3.2",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "3.3",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "3.4",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "3.5",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "3.6",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "3.7",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "null",
      "date": "2018-02-08",
      "downloads": 1
    }
  ],
  "package": "package_name",
  "type": "python_minor_downloads"
}</code></pre>
    </p>
    <h3>/api/packages/&lt;package&gt;/system</h3>
    <p>Retrieve the aggregate daily download time series by operating system.
    </p>
    <p>Query arguments:
    <ul>
        <li>
            <b>os</b>
            (optional): the operating system name, e.g.
            <code>windows</code>,
            <code>linux</code>,
            <code>darwin</code>
            or
            <code>other</code>. If omitted returns all series data (including
            <code>null</code>).
        </li>
        <!-- <li> <b>start_date</b> (optional): starting date of time series in format <code>YYYY-MM-DD</code> </li> <li> <b>end_date</b> (optional): ending date of time series in format <code>YYYY-MM-DD</code> </li> -->
    </ul>
    Example response:
    <pre><code>{
  "data": [
    {
      "category": "darwin",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "linux",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "null",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "other",
      "date": "2018-02-08",
      "downloads": 1
    },
    {
      "category": "windows",
      "date": "2018-02-08",
      "downloads": 1
    }
  ],
  "package": "package_name",
  "type": "system_downloads"
}</code></pre>
    </p>

{% endblock %}

pypistats/templates/index.html
{% extends "layout.html" %}
{% block title %}PyPI Download Stats{% endblock %}
{% block body %}
    <h1>Analytics for PyPI packages</h1>
    <hr>
    <form method="POST" action="/">
        {{ form.csrf_token }}
        {{ form.name.label }}
        {{ form.name(size=24) }}
        <input type="submit" value="Search">
    </form>
    <br>
    {% if not search %}
        <p>Search among
            <b>{{ "{:,.0f}".format(package_count) }}</b>
            python packages from PyPI (updated daily).</p>
    {% else %}
        Search results:
    {% endif %}
    {% if search %}
        <br>
        {% include "results.html" %}
    {% endif %}
{% endblock %}

pypistats/templates/layout.html
<!doctype html>
<html>

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-101875606-5"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-101875606-5');
    </script>
    <link rel="stylesheet" href="/static/style.css">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="description" content="PyPI Download Stats">
    <meta name="keywords" content="Python,PyPI,package,downloads,stats">
    <title>
        {% block title %}{% endblock %}
    </title>
    <meta name="viewport" content="width=device-width">
    <!--[if lt IE 9]> <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
            type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.0.0/anchor.min.js" type="text/javascript"></script>
    <!-- Place this tag in your head or just before your close body tag. -->
    {% block plot %}{% endblock %}
    {% block auth %}{% endblock %}
</head>

<body>
<div class="wrapper">
    <header>

        <h1>PyPI Stats</h1>
        <p>
            <a href="{{ url_for('general.index') }}">Search</a>
            <br>
            <br>
            <a href="{{ url_for('general.package_page', package='__all__') }}">All packages</a>
            <br>
            <a href="{{ url_for('general.top') }}">Top packages</a>
            <br>
            <br>
            {% if user %}
                <a href="{{ url_for('user.user') }}">{{ user.username }}'s packages</a>
            {% else %}
                <a href="{{ url_for('user.user') }}">Track packages</a>
            {% endif %}
            <br>
            <br>
            {% if user %}
                <a href="{{ url_for('user.logout') }}">Logout</a>
            {% endif %}
        </p>

    </header>

    <section>
        {% block body %}{% endblock %}
    </section>

    <footer>
        <p>
            <a href="{{ url_for('api.api') }}">API</a>
            <br>
            <a href="{{ url_for('general.about') }}">About</a>
            <br>
            <a href="{{ url_for('general.faqs') }}">FAQs</a>
            <br>
        </p>
    </footer>
</div>
<script>
    anchors.add();
</script>

</body>

</html>

pypistats/templates/package.html
{% extends "layout.html" %}
{% block title %}PyPI Download Stats{% endblock %}
{% block plot %}
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
{% endblock %}
{% block body %}
    <h1>{{ package }}</h1>
    <hr>
    {% if user %}
        {% if user.favorites and package in user.favorites %}
            <p>
                <img src="{{ user.avatar_url }}" height="20" width="20">
                <a href="{{ url_for('user.user_package', package=package) }}">REMOVE from my packages</a><br></p>
        {% else %}
            <p>
                <img src="{{ user.avatar_url }}" height="20" width="20">
                <a href="{{ url_for('user.user_package', package=package) }}">ADD to my packages</a><br></p>
        {% endif %}
    {% endif %}
    {% if package == "__all__" %}
        <p>Download stats for __all__ indicate downloads across all packages on PyPI.</p>
    {% else %}
        <p>
        {% if metadata %}
            <a href="{{ metadata['info']['package_url'] }}">PyPI page</a>
            <br>
            <a href="{{ metadata['info']['home_page'] }}">Home page</a>
            <br>
            Author:
            {{ metadata['info']['author'] }}
            {% if metadata['info']['license'] is not none %}
                <br>
                License:
                {% if metadata['info']['license'] | length > 200 %}
                    {{ metadata['info']['license'][:200] }}...
                {% else %}
                    {{ metadata['info']['license'] }}
                {% endif %}
            {% endif %}
            <br>
            Summary:
            {{ metadata['info']['summary'] }}
            <br>
            Latest version:
            {{ metadata['info']['version'] }}
            <br>
            {% if metadata['requires'] %}
                Required dependencies:
                {% for required in metadata['requires'] %}
                    <a href="{{ url_for('general.package_page', package=required.lower()) }}">{{ required.lower() }}</a>
                    {% if not loop.last %}|{% endif %}
                {% endfor %}
            {% endif %}
            {% if metadata['optional'] %}
                <br>
                Optional dependencies:
                {% for optional in metadata['optional'] %}
                    <a href="{{ url_for('general.package_page', package=optional.lower()) }}">{{ optional.lower() }}</a>
                    {% if not loop.last %}|{% endif %}
                {% endfor %}
            {% endif %}
        {% else %}
            No metadata found.
        {% endif %}
    {% endif %}
<br>
<br>
Downloads last day:
{{ "{:,.0f}".format(recent['day']) }}
<br>
Downloads last week:
{{ "{:,.0f}".format(recent['week']) }}
<br>
Downloads last month:
{{ "{:,.0f}".format(recent['month']) }}
</p>
    <script>

        (function () {
            var WIDTH_IN_PERCENT_OF_PARENT = 100
            // var HEIGHT = '300px'
            var divelems = []

            var data =
            {{ plots|tojson }}

            for (plt in data) {
                var gd3 = Plotly.d3.select('section').append('div').style({
                    width: WIDTH_IN_PERCENT_OF_PARENT + '%',
                    'margin-left': (100 - WIDTH_IN_PERCENT_OF_PARENT) / 2 + '%',
                    // height: HEIGHT,
                })
                var gd = gd3.node()
                divelems.push(gd)
                Plotly.newPlot(divelems[divelems.length - 1], data[plt].data, data[plt].layout, data[plt].config);
            }
            window.onresize = function () {
                for (chart in divelems) {
                    Plotly.Plots.resize(divelems[chart]);
                }
            };
        })();
    </script>
{% endblock %}

pypistats/templates/results.html
<br>
{% if packages %}
    <ul>
        {% for package in packages %}
            <li>
                <a href="{{ url_for('general.package_page', package=package) }}">{{ package }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    No results.
{% endif %}

pypistats/templates/search.html
{% include "index.html" %}

pypistats/templates/top.html
{% extends "layout.html" %}
{% block title %}PyPI Download Stats{% endblock %}
{% block body %}
    <h1>Most downloaded PyPI packages</h1>
    <hr>
    <table>
        <tr>
            {% for best in top %}
                <td>
                    Most downloaded past
                    <b>{{ best['category'].lower() }}</b>.
                </td>
            {% endfor %}
        </tr>
        <tr>
            {% for best in top %}
                <td>
                    <table>
                        {% for package in best['packages'] %}
                            <tr>
                                <td>
                                    {{ loop.index }}
                                </td>
                                <td>
                                    <a href="{{ url_for('general.package_page', package=package['package']) }}">{{ package['package'] }}</a>
                                </td>
                                <td>
                                    {{ "{:,.0f}".format(package['downloads']) }}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </td>
            {% endfor %}
        </tr>
    </table>
{% endblock %}

pypistats/templates/user.html
{% extends "layout.html" %}
{% block title %}PyPI Download Stats{% endblock %}
{% block body %}
    {% if user %}

        <h1><img src="{{ user.avatar_url }}" height="25" width="25">
            {{ user.username }}'s Packages</h1>
        <hr>
        <p>Currently saved packages.</p>
        {% if user.favorites %}
            <p>
            <ul>
                {% for package in user.favorites %}
                    <li>
                        <a href="{{ url_for('general.package_page', package=package) }}">{{ package }}</a>
                    </li>
                {% endfor %}
            </ul>
            </p>
        {% else %}
            <p>Not tracking any packages.</p>
        {% endif %}
    {% else %}
        <h1>My Packages</h1>
        <hr>
        <p>Log in with GitHub OAuth to track your own set of packages.</p>
        <p>
            <a href="{{ url_for('user.login') }}">Log in</a>
        </p>
    {% endif %}
{% endblock %}